## What is an array?
<br> An array is a collection of objects. 
<br> Objects in same aray must be the same type. 
<br> Multidimensional arrays are standard. 
<br> Arrays are denoted by square brackets. 
<br> Array entries are separated by spaces. 
<br> Entries are indexed, starting with 0. 
<br> Python is optimized for arrays. 
<br> Standard operators work entry by entry. 
<br> Functions can work entry by entry. 
<br> Once created, arrays are fixed in size. 
<br> len(an_array) returns  the numbers of rows. 
<br> We will use numpy arrays.


In [3]:
import numpy as np
array_0=np.zeros(4,float)
array_1=np.ones(4,complex)
array_2=np.full([2,3], 23) #specify initial value for all entries
array_3=np.full_like(array_2,2) #zero_like and one_like work the same way, 
#same dimensions as array_2 filled with 2

print(array_0)
print(array_1)
print(array_2)
print(array_3)


[0. 0. 0. 0.]
[1.+0.j 1.+0.j 1.+0.j 1.+0.j]
[[23 23 23]
 [23 23 23]]
[[2 2 2]
 [2 2 2]]


In [9]:
mk_array=np.array([11,12,13], int) #provide alist as an argument
print("make array", mk_array)

my_list=[22,23,24]
my_list_array=np.array(my_list,int)
print("list array", my_list_array)
#careful of empty and empty_like - they will be filled with whatever happens 
#to be in those memory locations
array_4=np.empty(3,float)
print(array_4)
input()
array_4=np.zeros(4,int)
print(array_4)

array_4+=2 #add 2 to all entries
print(array_4)

array_4 *=3 # multiplyall entries by 3
print(array_4)

array_5=np.ones(4,int)
print(array_5)
array_4+=array_5
print(array_4)

make array [11 12 13]
list array [22 23 24]
[ 1.24610723e-306  9.10865418e-312 -0.00000000e+000]
1
[0 0 0 0]
[2 2 2 2]
[6 6 6 6]
[1 1 1 1]
[7 7 7 7]


In [21]:
array_bin_0 = np.full(4,0)
array_bin_1 = np.full(4,1) 
array_bin_0[2]=1
array_bin_0[3]=1
array_bin_1[0]=0
array_bin_1[2]=0
print("", array_bin_0, "\n", array_bin_1)
array_bin_2=array_bin_0&array_bin_1
array_bin_3=array_bin_0|array_bin_1

print("and:\n", array_bin_2, "\nor:\n", array_bin_3)

array_6=array_5
print(array_5)
array_6[0]=1000
print("changed", array_5)
array_7=np.copy(array_5)
array_7[0]=23
print("\nno change", array_5)
print(array_7)

#######################
#zip combines arrays into tuples
array_x = np.arange(0,10,1)
array_y=np.arange(10,20,1)
for x_val, y_val in zip(array_x, array_y): #makes tuple of pairs
    print(x_val,  y_val)
    
grid_x, grid_y = np.meshgrid(array_x, array_y)
print(array_x, "\n\n")
print(array_y, "\n\n")
print("grid_x:\n", grid_x, "\n\n")
print("grid_y:\n", grid_y, "\n\n")

 [0 0 1 1] 
 [0 1 0 1]
and:
 [0 0 0 1] 
or:
 [0 1 1 1]
[1000    1    1    1]
changed [1000    1    1    1]

no change [1000    1    1    1]
[23  1  1  1]
0 10
1 11
2 12
3 13
4 14
5 15
6 16
7 17
8 18
9 19
[0 1 2 3 4 5 6 7 8 9] 


[10 11 12 13 14 15 16 17 18 19] 


grid_x:
 [[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]] 


grid_y:
 [[10 10 10 10 10 10 10 10 10 10]
 [11 11 11 11 11 11 11 11 11 11]
 [12 12 12 12 12 12 12 12 12 12]
 [13 13 13 13 13 13 13 13 13 13]
 [14 14 14 14 14 14 14 14 14 14]
 [15 15 15 15 15 15 15 15 15 15]
 [16 16 16 16 16 16 16 16 16 16]
 [17 17 17 17 17 17 17 17 17 17]
 [18 18 18 18 18 18 18 18 18 18]
 [19 19 19 19 19 19 19 19 19 19]] 




In [28]:
import numpy as np
array_0 = np.zeros(4,int)
array_1 = np.zeros(4,int)

for index in range(4): 
    array_0[index] = index
    array_1[index] = (index *2) +1
    
print(array_0)
print(array_1)

array_3=array_0*array_1 # element by element multiplication
print(array_3)

array_4=np.zeros([1,4],int)
array_5=np.zeros([4,1],int)
for index in range(4): 
        array_4[0,index] = 1+index
        array_5[index,0] = (index+1) **2

print(array_4)
print(array_5)

my_dot=np.dot(array_4,array_5) #form dot product
print(my_dot)

my_dot=np.dot(array_5,array_4) #very different result when you reverse the dot
#product
print(my_dot)



[0 1 2 3]
[1 3 5 7]
[ 0  3 10 21]
[[1 2 3 4]]
[[ 1]
 [ 4]
 [ 9]
 [16]]
[[100]]


In [34]:
print("array_4 size", array_4.size)
print("array_4 shape", array_4.shape)
print("array_4 len", len(array_4))
print("array_4 size", my_dot.size)
print("array_4 shape", my_dot.shape)
print("my_dot len", len(my_dot))

input_data = np.loadtxt("m2_arrays2.txt", int)
print(input_data)

print(input_data[0,:])
print(input_data[0,2:3])
print(input_data[:,2])
print(input_data[:1,3])

array_4 size 4
array_4 shape (1, 4)
array_4 len 1
array_4 size 1
array_4 shape (1, 1)
my_dot len 1
[[  3   8  11  27   9]
 [  2 100  -4  34  56]]
[ 3  8 11 27  9]
[11]
[11 -4]
[27]


## Today's Objectives
<br> Learn how to get information about Python objects
<br> Understand exceptions
<br> Use exceptions


In [4]:
import keyword
print(keyword.kwlist)

print(dir(keyword))
print("is 'and' a keyword", keyword.iskeyword("and"))
print("is 'AND' a keyword", keyword.iskeyword("AND"))


['False', 'None', 'True', 'and', 'as', 'assert', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
['__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'iskeyword', 'kwlist', 'main']
is 'and' a keyword True
is 'AND' a keyword False


In [5]:
help(str)

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |  
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(...)
 |      S.__format__(format_spec) -> str
 |      
 |      Return a formatted version of S as described by format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getatt

## help(str) continued
<br> Shows private and public methods
<br> methods are functions defined for objects
<br> self is a reference to the calling string
<br> my_string = 'hello world'
<br> words = my_string.split()
<br> In the method, self is understood and not specified. 
<br> If the help page is longer than a screen, the colon appears. 
<br> Hit spacebar to advance to the next page. 
<br> Hit the return key to advance one line. 

## Exception Catching
<br> Exceptions cause programs to crash
<br> Exceptions can be due to bad code Fix before shipping!
<br> Exceptions can be due to bad data Python can catch these!
<p> Examples: 
<br> ZeroDivision Error, TypeError, RecursionError

In [7]:
try: 
    bad_div = 12/0 #can be a full block of code
except: 
    print("don't do that!")
    
try: 
    bad_div = 12/0 #can be a full block of code
except ZeroDivisionError: 
    print("ZeroDivisionError - still don't do that!")
except: 
    print("some other exception")
    
try: 
    bad_div = 12/0 #can be a full block of code
except TypeError: 
    print("TypeError - still don't do that!")
except: 
    print("some other exception")

don't do that!
ZeroDivisionError - still don't do that!
some other exception


## Strings and Files
<br> Learn how to manipulate strings
<br> Understand how to open and close files
<br> Be able to read and write files


In [8]:
help(str.split)

Help on method_descriptor:

split(...)
    S.split(sep=None, maxsplit=-1) -> list of strings
    
    Return a list of the words in S, using sep as the
    delimiter string.  If maxsplit is given, at most maxsplit
    splits are done. If sep is not specified or is None, any
    whitespace string is a separator and empty strings are
    removed from the result.



In [14]:
my_string = "Once upon a time"
print("this is my_string:", my_string)
my_words = my_string.split()
print("my_words is a list:", my_words)
print("my string did not change:", my_string)

for word in my_words: 
    print("iterate on list items:", word)

for index in range(len(my_words)): 
    print("iterate by index:", my_words[index])

str1='what a fine day this is'
print(str1.split())
print(str1.split('f'))
print(str1.split('i'))

delim = '@'                    #use this as the joining character
my_tuple = ('a', 'b', 'c')
my_list = ['d', 'e', 'f']
print(delim.join(my_tuple))
print(delim.join(my_list))

delim=''                       # don't like anything in between
print(delim.join(my_tuple))
print(delim.join(my_list))

delim=' '                       #put a space in between
print(delim.join(my_tuple))
print(delim.join(my_list))

this is my_string: Once upon a time
my_words is a list: ['Once', 'upon', 'a', 'time']
my string did not change: Once upon a time
iterate on list items: Once
iterate on list items: upon
iterate on list items: a
iterate on list items: time
iterate by index: Once
iterate by index: upon
iterate by index: a
iterate by index: time
['what', 'a', 'fine', 'day', 'this', 'is']
['what a ', 'ine day this is']
['what a f', 'ne day th', 's ', 's']
a@b@c
d@e@f
abc
def
a b c
d e f


In [17]:
my_inp_file = open("m2_str_io.txt", "r") # r is default, add a b for binary
my_out_file = open("m2_str_io.out", "w") # to append, use "a" instead of "w"

for line in my_inp_file:                #neat way to get a line at a time to 
    print(line)                         #to process, note extra carriage return
    my_out_file.write(line)             #print always adds carriage return
    
my_inp_file.close()                      # always close when done
my_out_file.close()                      #forgetting to close is a common error

How now brown cow

What if you can keep your head



One more time



In [23]:
my_inp_file = open("m2_str_io.txt","r")
one_line = my_inp_file.readline() # read one line at a time
print(one_line)
another_line = my_inp_file.readline()
input()
print(another_line)
input()
print("end of print")
remove_stuff = another_line.strip() # removes white space, theres also lstrip
print(remove_stuff)                 # and rstrip (left end or right end)
print("end of print")

del_d = remove_stuff.strip('e')
print(del_d)

How now brown cow

1
What if you can keep your head

1
end of print
What if you can keep your head
end of print
What if you can keep your head
